# API-specific profile: tag handling, security schemes, custom types.
# Main loads private.profile if it exists, otherwise this file (they are alternatives, not merged).
# Keep API-specific values in private.profile (gitignored); this file documents the syntax
# and, being empty, keeps the generator fully neutral.

# Endpoints tagged with any of these tags are dropped entirely.
#tags.ignored=SomeTag,OtherTag

# Tags matching this regex are rejected as malformed (e.g. autogenerated "foo-controller" tags).
#tags.reject.regex=-

# Tag renaming/collapsing: comma-separated From>To entries.
#tags.collapse=dog>pet,cat>pet

# A dominant tag removes all other tags of an endpoint.
#tags.dominant=pet

# Names of security schemes handled inside generated repos (token injection, optional security).
#security.jwt=JWT
#security.xsrf=X-XSRF-TOKEN

# Access-level grouping (public vs logged-in, split by JWT presence; needs security.jwt):
# endpoints whose name fully matches a regex are forced into that group regardless of security,
# endpoints carrying any of the listed tags are forced into the logged-in group (the regexes win).
# Typical use: login/token endpoints require no JWT but belong to the logged-in area.
#groups.loggedIn.regex=login|jwt
#groups.public.regex=healthCheck
#groups.loggedIn.tags=Auth

# Param preprocessing rules "fromFormat|toFormat|guardTypeKey", separated by ';':
# params of format fromFormat are rewritten to toFormat unless a param of type guardTypeKey is present.
#params.formatFallback=ID:Pet.ID|ID:Pet.IncompleteID|PET_TYPE

# Custom scalar types registered in TypeResolver; rows separated by ';', fields by '|'.
# 3 fields:  transportType|format|kotlinTransport                                            (same type on both sides)
# 6 fields:  transportType|format|kotlinTransport|kotlinDomain|toDomainExpr|toTransportExpr  (%s = converted value)
#types.custom=\
#	string|myFormat|String;\
#	integer|myId|Long|MyId|MyId(%s)|%s.internal;
