package models

import java.util.Properties

/**
 * API-specific customizations (tag handling, security schemes, custom types).
 * Loaded from private.profile if it exists, otherwise app.profile — like private.config/app.config.
 * Every key is optional; with an empty Properties the profile is neutral and changes nothing.
 */
class Profile constructor(props: Properties) {

	/** endpoints tagged with any of these tags are dropped entirely */
	val ignoredTags: List<String> = props.list("tags.ignored")

	/** tags matching this regex are rejected as malformed (e.g. autogenerated ones) */
	val tagRejectRegex: Regex? = props.getProperty("tags.reject.regex")?.toRegex()

	/** tag renaming/collapsing: comma-separated "From>To" entries */
	val tagCollapse: Map<String, String> = props.list("tags.collapse")
		.associate { entry ->
			val parts = entry.split('>')
			require(parts.size == 2) { "malformed tags.collapse entry: $entry" }
			parts[0].trim() to parts[1].trim()
		}

	/** a dominant tag removes all other tags of an endpoint */
	val dominantTags: List<String> = props.list("tags.dominant")

	/** name of the JWT security scheme; enables optional-security and generated token handling */
	val jwtScheme: String? = props.getProperty("security.jwt")

	/** name of the XSRF security scheme handled inside generated repos */
	val xsrfScheme: String? = props.getProperty("security.xsrf")

	/** endpoints (by name) forced into the logged-in access group despite requiring no JWT, e.g. login/token calls */
	val loggedInOverrideRegex: Regex? = props.getProperty("groups.loggedIn.regex")?.toRegex()

	/** endpoints (by name) forced into the public access group despite requiring JWT */
	val publicOverrideRegex: Regex? = props.getProperty("groups.public.regex")?.toRegex()

	/** endpoints carrying any of these tags are forced into the logged-in access group; the name regexes win */
	val loggedInTags: List<String> = props.list("groups.loggedIn.tags")

	/**
	 * custom scalar types registered in TypeResolver; rows separated by ';', fields by '|':
	 * transportType|format|kotlinTransport                                          (same type on both sides)
	 * transportType|format|kotlinTransport|kotlinDomain|toDomainExpr|toTransportExpr (converted, %s = value)
	 */
	val customTypes: List<CustomType> = props.rows("types.custom") { fields, row ->
		val format = fields.getOrNull(1)?.ifEmpty { null }
		when (fields.size) {
			3 -> CustomType(fields[0], format, fields[2], fields[2], "%s", "%s")
			6 -> CustomType(fields[0], format, fields[2], fields[3], fields[4], fields[5])
			else -> throw IllegalArgumentException("malformed types.custom row: $row")
		}
	}

	/**
	 * This is strange one and hard to explain. It's purpose is to ease out overly restrictive IDs.
	 * Assuming Pet.PartialID(val id: Long) and Pet.FullID(id: Long, val type: PET_TYPE): IncompleteID(id)
	 * and FullID being the default name in API despite being in fact Partial.ID
	 * this weird one changes method arguments from Full to Partial
	 * - unless a second argument of PET_TYPE is also present.
	 *
	 * The use case is when a project is started using id named just Pet.ID and well into it you decide that
	 * this is better compounded with something else, so the API and the client no longer agree on what that ID is.
	 *
	 * param preprocessing rules, rows "fromFormat|toFormat|guardTypeKey":
	 * params of format fromFormat are rewritten to toFormat unless a param of type guardTypeKey is present
	 */
	val paramFormatFallbacks: List<ParamFormatFallback> = props.rows("params.formatFallback") { fields, row ->
		require(fields.size == 3) { "malformed params.formatFallback row: $row" }
		ParamFormatFallback(fields[0], fields[1], fields[2])
	}

	data class CustomType(
		val transportType: String,
		val format: String?,
		val kotlinTransport: String,
		val kotlinDomain: String,
		val toDomainAdapter: String,
		val toTransportAdapter: String,
	)

	data class ParamFormatFallback(
		val fromFormat: String,
		val toFormat: String,
		val guardTypeKey: String,
	)

	private fun Properties.list(key: String): List<String> =
		getProperty(key)?.split(',')?.map { it.trim() }?.filter { it.isNotEmpty() } ?: emptyList()

	private fun <T> Properties.rows(key: String, parse: (fields: List<String>, row: String) -> T): List<T> =
		getProperty(key)?.split(';')
			?.map { it.trim() }
			?.filter { it.isNotEmpty() }
			?.map { row -> parse(row.split('|').map { it.trim() }, row) }
			?: emptyList()

	companion object {
		/** set once by Main before parsing/generation; defaults to a neutral profile */
		var active = Profile(Properties())
	}
}
