package models

data class Tag(override val key: String) : EndpointGroup {
	override fun toString() = key

	init {
		//skip autogenerated tags
		if (key.contains("-"))
			throw IllegalArgumentException("invalid tag: $key")
	}

}