package models

data class Tag(override val key: String) : EndpointGroup {
	override fun toString() = key

	init {
		//skip malformed tags (e.g. autogenerated ones), as configured in the profile
		if (Profile.active.tagRejectRegex?.containsMatchIn(key) == true)
			throw IllegalArgumentException("invalid tag: $key")
	}

}